const projects = [
  {
    id: 1,
    title: 'Eat Seasonal',
    tech: [
      'React',
      'Express',
      'Node.js',
      'Javascript',
      'Teamwork',
      'Full stack',
    ],
    desktop: false,
    mobile: true,
    githubUrl:
      'https://github.com/SchoolOfCode/final-project-repo-restful-journey/blob/main/README.md',
    websiteUrl: 'https://seasonal-food.netlify.app/',
    introduction:
      'The app provides recipes around in season produce, allowing a user to create an account, shopping list and save favourite recipes as well.',
    imageUrl: './images/nourish.png',
    imageAlt: 'Eat Seasonal',
  },
  {
    id: 2,
    title: 'onePlace',
    tech: [
      'React',
      'Express',
      'Node.js',
      'Javascript',
      'Teamwork',
      'Full stack',
    ],
    desktop: true,
    mobile: false,
    githubUrl: 'https://github.com/Luis0lo',
    websiteUrl: 'https://agitated-northcutt-ed9a89.netlify.app/',
    introduction:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad dolor dolore placeat adipisci, in dicta voluptas, nihil animi facere quis dolorem ab, mollitia iure molestias nobis facilis nemo ut iste.',
    imageUrl: '/images/onePlace.jpg',
    imageAlt: 'One place',
  },
  {
    id: 3,
    title: 'Investiment Tracker',
    tech: ['React', 'Express', 'Node.js', 'Personal', 'Full stack'],
    desktop: true,
    mobile: true,
    githubUrl: 'https://github.com/Luis0lo/Hold_React',
    websiteUrl: 'https://holdreact.netlify.app/holdings',
    introduction:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad dolor dolore placeat adipisci, in dicta voluptas, nihil animi facere quis dolorem ab, mollitia iure molestias nobis facilis nemo ut iste.',
    imageUrl: '/images/hold.jpg',
    imageAlt: 'Investment tracker',
  },
  {
    id: 4,
    title: 'Weather App',
    tech: ['React', 'Personal'],
    desktop: true,
    mobile: true,
    githubUrl: 'https://github.com/Luis0lo/Hold_React',
    websiteUrl: 'https://holdreact.netlify.app/weather',
    introduction:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad dolor dolore placeat adipisci, in dicta voluptas, nihil animi facere quis dolorem ab, mollitia iure molestias nobis facilis nemo ut iste. ',
    imageUrl: '/images/weather.jpg',
    imageAlt: 'Weather App',
  },
  {
    id: 5,
    title: 'El Duque Real',
    tech: ['Freelance', 'Bootstrap'],
    desktop: true,
    mobile: true,
    githubUrl: 'https://github.com/Luis0lo/Duque-Real',
    websiteUrl: 'https://www.elduquereal.com/',
    introduction:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad dolor dolore placeat adipisci, in dicta voluptas, nihil animi facere quis dolorem ab, mollitia iure molestias nobis facilis nemo ut iste. ',
    imageUrl: '/images/duquereal.jpg',
    imageAlt: 'Static Website El Duque Real',
  },
  {
    id: 6,
    title: 'Islandscape',
    tech: ['Javascript', 'Personal'],
    desktop: true,
    mobile: true,
    githubUrl: 'https://github.com/Luis0lo/Static-Web',
    websiteUrl: 'https://luis0lo.github.io/Static-Web/',
    introduction:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad dolor dolore placeat adipisci, in dicta voluptas, nihil animi facere quis dolorem ab, mollitia iure molestias nobis facilis nemo ut iste. ',
    imageUrl: '/images/island.jpg',
    imageAlt: 'Static Website Islandscape',
  },
  {
    id: 7,
    title: 'Fields',
    tech: [
      'Mongo',
      'Express',
      'Node.js',
      'Javascript',
      'Personal',
      'Full stack',
    ],
    desktop: true,
    mobile: true,
    githubUrl: 'https://github.com/Luis0lo/field',
    websiteUrl: 'https://fieldsapp.herokuapp.com/',
    introduction:
      'Lorem ipsum dolor sit amet consectetur adipisicing elit. Ad dolor dolore placeat adipisci, in dicta voluptas, nihil animi facere quis dolorem ab, mollitia iure molestias nobis facilis nemo ut iste. ',
    imageUrl: '/images/fields.jpg',
    imageAlt: 'Fields',
  },
];
export default projects;
