const projects = [
  {
    id: 1,
    title: 'Eat Seasonal',
    tech: [
      'React',
      'Express',
      'Node.js',
      'Javascript',
      'Teamwork',
      'Full stack',
    ],
    onlyMobile: true,
    githubUrl:
      'https://github.com/SchoolOfCode/final-project-repo-restful-journey/blob/main/README.md',
    websiteUrl: 'https://seasonal-food.netlify.app/',
    introduction:
      'The app provides recipes around in season produce, allowing a user to create an account, shopping list and save favourite recipes as well.',
    imageUrl: './images/nourish.png',
    imageAlt: 'Eat Seasonal',
  },
  {
    id: 2,
    title: 'onePlace',
    tech: [
      'React',
      'Express',
      'Node.js',
      'Javascript',
      'Teamwork',
      'Full stack',
    ],
    onlyMobile: false,
    githubUrl: 'https://github.com/Luis0lo',
    websiteUrl: 'https://agitated-northcutt-ed9a89.netlify.app/',
    introduction: 'description',
    imageUrl: '/images/onePlace.jpg',
    imageAlt: 'One place',
  },
  {
    id: 3,
    title: 'Hold',
    tech: [
      'React',
      'Express',
      'Node.js',
      'Javascript',
      'Personal',
      'Full stack',
    ],
    githubUrl: 'https://github.com/Luis0lo/Hold_React',
    websiteUrl: 'https://holdreact.netlify.app/holdings',
    introduction:
      'description',
    imageUrl: '/images/hold.jpg',
    imageAlt: 'Hold',
  },{
    id: 4,
    title: 'Weather App',
    tech: [
      'React',
      'Express',
      'Node.js',
      'Javascript',
      'Personal',
      'Full stack',
    ],
    githubUrl: 'https://github.com/Luis0lo/Hold_React',
    websiteUrl: 'https://holdreact.netlify.app/holdings',
    introduction:
      'description ',
    imageUrl: '/images/weather.jpg',
    imageAlt: 'duquereal',
  },
  {
    id: 5,
    title: 'El Duque Real',
    tech: [
      'React',
      'Express',
      'Node.js',
      'Javascript',
      'Personal',
      'Full stack',
    ],
    githubUrl: 'https://github.com/Luis0lo/Hold_React',
    websiteUrl: 'https://holdreact.netlify.app/holdings',
    introduction:
      'description ',
    imageUrl: '/images/duquereal.jpg',
    imageAlt: 'duquereal',
  },
  {
    id: 6,
    title: 'Islandscape',
    tech: [
      'React',
      'Express',
      'Node.js',
      'Javascript',
      'Personal',
      'Full stack',
    ],
    githubUrl: 'https://github.com/Luis0lo/Hold_React',
    websiteUrl: 'https://holdreact.netlify.app/holdings',
    introduction:
      'description ',
    imageUrl: '/images/island.jpg',
    imageAlt: 'duquereal',
  },{
    id: 7,
    title: 'Fields',
    tech: [
      'Mongo',
      'Express',
      'Node.js',
      'Javascript',
      'Personal',
      'Full stack',
    ],
    githubUrl: 'https://github.com/Luis0lo/Hold_React',
    websiteUrl: 'https://holdreact.netlify.app/holdings',
    introduction:
      'description ',
    imageUrl: '/images/fields.jpg',
    imageAlt: 'fields',
  },
];
export default projects;
